---
title: "model"
output:
  pdf_document:
    number_sections: yes
    latex_engine: xelatex
  word_document: default
fig_caption: yes
---


```{r setup, include=FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, warning=FALSE, message=FALSE)
```

```{r,echo = FALSE}
data1 <- read.csv("C:/Users/Seismic/Downloads/dataset3.csv")
data1 <- data1 %>% 
    mutate(Type.single = ifelse(Type.of.Household =="Single Family", "1", "0"))
data1[,"Total.Number.of.Family.members"] <- ifelse(data1[,"Total.Number.of.Family.members"] > median(data1[,"Total.Number.of.Family.members"]),1,0)
data1$Total.Number.of.Family.members<-as.factor(data1$Total.Number.of.Family.members)

model2 <-  glm(Total.Number.of.Family.members ~ 
                   log(Total.Household.Income)+
                   log(Total.Food.Expenditure)+
                   Household.Head.Age+
                   House.Age+
                   Electricity+
                   Household.Head.Sex+
                   Type.single,family = binomial(link = "logit"),data = data1)
#CI
confint(model2)%>%
  kable
#Coef
model2 %>%
 coef() %>%
  exp()
knitr::kable(model2, caption = 'Coefficients')
#Reducing the income of total household
#Increasing the expenditure of food
#The less age of the head in household, the more the number
#The less house age
#House that does not have electricity
#The head of the household is male
#Single family is not good

#odds ratio plot
plot_model(model2, show.values = TRUE, 
           title = "Odds ratios", show.p = FALSE)
#prob
data1 <-  data1%>%
                  mutate(logodds = predict(model2))
data1 <- data1 %>%
                  mutate(odds = exp(logodds))
data1 <- data1 %>%
                  mutate(probs = fitted(model2))

p1<-ggplot(data = data1, aes(x = Total.Household.Income, y = probs)) +
  geom_smooth(method="glm", 
              method.args = list(family="binomial"), 
              se = FALSE) +
  labs(x = "Income", y = "Prob of more family members")

p2<-ggplot(data = data1, aes(x = Total.Food.Expenditure, y = probs)) +
  geom_smooth(method="glm", 
              method.args = list(family="binomial"), 
              se = FALSE) +
  labs(x = "Expenditure", y = "Prob of more family members")

p3<-ggplot(data = data1, aes(x = Household.Head.Age, y = probs)) +
  geom_smooth(method="glm", 
              method.args = list(family="binomial"), 
              se = FALSE) +
  labs(x = "Household head age", y = "Prob of more family members")

p4<-ggplot(data = data1, aes(x = House.Age, y = probs)) +
  geom_smooth(method="glm", 
              method.args = list(family="binomial"), 
              se = FALSE) +
  labs(x = "House age", y = "Prob of more family members")

grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)

#categories variables pro plot
plot_model(model2, type = "pred", title = "",
           axis.title = c("Ethnicity", "Probability of more family members"))

data1$predFull<-predict(model2,type="response",na.action=na.exclude)
score<-prediction(data1$predFull,data1$Total.Number.of.Family.members)
perf<-performance(score,"tpr","fpr")
auc<-performance(score,"auc")
perfd<-data.frame(x=perf@x.values[1][[1]],y=perf@y.values[1][[1]])
roc.trump<-ggplot(perfd,aes(x=x, y=y))+geom_line()+
  xlab("False postive rate")+ylab("True positive rate")+
  ggtitle(paste("Area under the curve:",round(auc@y.values[[1]],3)))
roc.trump

#Area under the curve is 0.812, we can improve the model performance by adding more meaningful variables and reducing some variables like house age nad household head age. 

#accuracy
data1$predFull<-predict(model2,type="response",na.action=na.exclude)
confM<-confusion.matrix(data1$Total.Number.of.Family.members,data1$predFull,threshold = 0.48)
sum(diag(confM))/sum(confM)
```




